# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-03 06:08
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0008_auto_20161202_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anevent',
            name='website',
        ),
        migrations.AddField(
            model_name='anevent',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='anevent',
            name='end_time',
            field=models.TimeField(default=datetime.time(16, 0)),
        ),
        migrations.AddField(
            model_name='anevent',
            name='start_time',
            field=models.TimeField(default=datetime.time(16, 0)),
        ),
        migrations.AddField(
            model_name='anevent',
            name='volunteer',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='anevent',
            name='volunteer_num',
            field=models.IntegerField(default=0),
        ),
    ]
