# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-03 06:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20161203_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anevent',
            name='end_time',
            field=models.TimeField(default=datetime.time(0, 0), help_text='ex: 10:30AM'),
        ),
        migrations.AlterField(
            model_name='anevent',
            name='start_time',
            field=models.TimeField(default=datetime.time(0, 0), help_text='ex: 10:30AM'),
        ),
    ]
